/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [
    {
      type: 'doc',
      id: 'intro'
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/installation',
        'getting-started/configuration',
      ],
      link: {
        type: 'generated-index'
      }
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [
        'core-concepts/styling',
        'core-concepts/typescript',
      ],
      link: {
        type: 'doc',
        id: 'core-concepts/overview'
      }
    },
    {
      type: 'category',
      label: 'Usage',
      items: [
        'usage/pages',
        'usage/theming',
        'usage/layouts',
        'usage/global-store',
        {
          type: 'category',
          label: 'Plugins',
          items: [
            'usage/plugins/access-control',
            'usage/plugins/authentication',
            'usage/plugins/data-fetching',
          ]
        },
        'usage/navigation',
      ],
      link: {
        type: 'generated-index'
      }
    },
    {
      type: 'doc',
      id: 'support'
    }
  ],
  api: [{type: 'autogenerated', dirName: 'api'}]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
